### ISSUE TITLE
Name not showing up

### ISSUE THREAD

**Issue by yevon** [r-renato/ha-card-waze-travel-time#2]
The card doesn't show the name of the waze travel time that I have, it shows empty:

(From and to columns)

![image](https://user-images.githubusercontent.com/121157/67982320-c4a8df80-fc22-11e9-8409-22c9e7658e4e.png)

**Comment by r-renato** [comment]
resolved @see [https://github.com/r-renato/ha-card-waze-travel-time/issues/3](issue3)

**Comment by yevon** [comment]
Thanks! solved
