### ISSUE TITLE
Blank Card

### ISSUE THREAD

**Issue by magicbret** [r-renato/ha-card-waze-travel-time#8]
Hi all,

I have an issue with this card. I have the name in the header but ta=hat's all. All the card is blank.

However, if i click on the card, i am redirected to Waze page with correct GPS coordinates, which mean that the datas are OK.

Here is how i configured the card:

      - type: custom:ha-card-waze-travel-time
        name: "Trajet vers..."
        unit: km
        columns:
          - from
          - to
          - duration
          - distance
          - icon
        destinations:
          - entity: sensor.waze_travel_time
            from: "Domicile"
            to: "Travail"

Screenshot: 

![Capture](https://user-images.githubusercontent.com/7100026/81574901-adebfe00-93a6-11ea-80b1-bbd5034dc30b.JPG)

And if i use standrd card, it's OK

![Capture2](https://user-images.githubusercontent.com/7100026/81575278-25219200-93a7-11ea-92e3-fdc07b73c81b.JPG)

Any suggestions ?

Thanks

**Comment by r-renato** [comment]
Hi, try to change color schema using the `style`. Check the readme for more details.

```
style: |
  ha-card {
    --primary-text-color: #FFFFFF;
    --secondary-text-color: #727272;
    --text-primary-color: #ffffff;
    --disabled-text-color: #bdbdbd;
    background-image: url("/local/imgs/card_back.png")
    background-repeat: no-repeat
    background-color: rgba(50,50,50,0.3)
    background-size: 100% 300px
    border-radius: 20px
    border: solid 1px rgba(100,100,100,0.3)
    box-shadow: 3px 3px rgba(0,0,0,0.4)
  }
```

**Comment by magicbret** [comment]
Thanks for your help. 

Unfortunately, even with having the good configuration, i still have a blank card. I can change with success the color of the title of the card, but cannot change the color of the content. Even the images do not work (but if i try to reach directly the pictures in my web broser, it's OK). I am out of idea :(

![Sans titre](https://user-images.githubusercontent.com/7100026/82042221-d24b2180-96a9-11ea-8f65-1960257766cd.png)

![Sans titre2](https://user-images.githubusercontent.com/7100026/82042452-2b1aba00-96aa-11ea-84da-de77857c44d4.png)

**Comment by r-renato** [comment]
I'm sorry, you're right, this is a minor bug. I have just now released a new version with the fix.

PS the css directives must end with a semicolon.

**Comment by magicbret** [comment]
Thanks :) and also for the semicolon :)

However, even with the update i cannot have something working. The only thing that works is to completely delete the style part, and i get a simple style.

I even tried with a basic conf like :

> 
style: |
  ha-card {
    color: blue;
  }

But still the same, and as you can see it's not really blue :-) 

![Sans titre3](https://user-images.githubusercontent.com/7100026/82071987-26202f80-96d7-11ea-95dc-21d6ec1d29a4.png)

**Comment by r-renato** [comment]
to change the text color you can use:

```
style: |
   ha-card {
   --primary-text-color: blue;
}
```
